baseURL = "https://elib.orekiyuta.cn"
languageCode = "en-us"
publishDir = "docs"
theme     = "bootie-docs"
title     = "Elib"

[params]
  highlightStyle = "github"
  description= "Elib is a Little Collection Library"
  searchDomain = "elib.orekiyuta.cn"
  withSitePosts  = true
  repositoryUrl  = "https://elib.orekiyuta.cn"



[[menu.main]]
  name   = "Tags"
  url    = "/Tags/"
  weight = 10